FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy producer script
COPY Kafka/realproducer.py producer.py

# Run the producer
CMD ["python", "producer.py"]
